version: 2
jobs:
  build:
    docker:
      - image: dwmkerr/terraform-ci:0.1.0
    steps:
      - checkout
      - run:
          name: Terraform Setup
          command: terraform init && terraform get
      - run:
          name: Terraform Lint
          command: make lint
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - image: dwmkerr/terraform-ci:0.1.0

workflows:
  version: 2
  test:
    jobs:
      - build
      - hold:
          requires:
            - build
          type: approval
      - test:
          requires:
            - hold
