# Job defaults, which are common across all jobs.
job_defaults: &job_defaults
  working_directory: /terraform-aws-openshift
  docker:
    - image: dwmkerr/terraform-ci:0.1.0
  environment:
    # We don't use the default ~/.ssh/id_rsa key, we create our own in the
    # workspace.
    - TF_VAR_public_key_path: "/terraform-aws-openshift/sshkey.pub" 

jobs:
  # Lint the Terraform code.
  lint:
    <<: *job_defaults
    steps:
      - checkout
      # Init Terraform.
      - run: terraform init && terraform get && terraform refresh
      - run:
          name: Terraform Lint
          command: make lint
      - persist_to_workspace:
          root: /terraform-aws-openshift
          paths:
            - .terraform

  # Create the plan, which we will manually approve. Deletes old infrastructure
  # first.
  plan:
    <<: *job_defaults
    steps:
      - checkout
      - attach_workspace:
          at:  /terraform-aws-openshift
      # Create the keypair for all future operations.
      - run:
          name: Create Keypair
          command: |
            ssh-keygen -b 2048 -t rsa -f /terraform-aws-openshift/sshkey -q -N ""
            ssh-add /terraform-aws-openshift/sshkey
      # Init Terraform. Cached in workflows, needed for running circle locally.
      - run: terraform init && terraform get && terraform refresh
      - run:
          name: Terraform Cleanup
          command: terraform destroy -force
      - run:
          name: Terraform Plan
          command: terraform plan
      - persist_to_workspace:
          root: /terraform-aws-openshift
          paths:
            - .terraform
            - sshkey

  # Apply the plan, creating the infrastructure.
  apply:
    <<: *job_defaults
    steps:
      - checkout
      - attach_workspace:
          at:  /terraform-aws-openshift
      # Init Terraform. Cached in workflows, needed for running circle locally. Also create the key.
      - run: |
            ssh-keygen -b 2048 -t rsa -f /terraform-aws-openshift/sshkey -q -N ""
            ssh-add /terraform-aws-openshift/sshkey
      - run: terraform init && terraform get && terraform refresh
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
      - persist_to_workspace:
          root: /terraform-aws-openshift
          paths:
            - .terraform

  # Destroy all old infrastructure.
  cleanup:
    <<: *job_defaults
    steps:
      - checkout
      - attach_workspace:
          at:  /terraform-aws-openshift
      # Init Terraform. Cached in workflows, needed for running circle locally.
      - run: terraform init && terraform get
      - run:
          name: Destroy AWS Infrastructure
          command: terraform destroy -force
      - persist_to_workspace:
          root: /terraform-aws-openshift
          paths:
            - .terraform
            - sshkey

workflows:
  version: 2
  test:
    jobs:
      - lint
      - plan:
          requires:
            - lint
          type: approval
      - apply:
          requires:
            - plan
